# Based off https://github.com/MinecraftForge/SharedActions/blob/main/.github/workflows/gradle.yml
name: Gradle Building CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle"
        required: false
        type: string
        default: "21"
      gradle_tasks:
        description: "The Gradle task(s) to run for building"
        required: false
        type: string
        default: "build"
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: The AES key to enable Gradle cache encryption
        required: false

permissions:
  contents: read

jobs:
  compute-suffix:
    runs-on: ubuntu-latest
    outputs:
      branch_suffix: ${{ steps.computeBranchSuffix.outputs.branch_suffix }}
    steps:
      - id: computeBranchSuffix
        name: "🔢 Compute branch suffix"
        run: |
          gitRef="${{ github.ref }}"
          branchName=$(echo "${gitRef/refs\/heads\//}")
          echo "Branch name: $branchName"
          
          cleanedBranchName=$(echo $branchName | sed 's/[^a-zA-Z0-9]/-/g')
          echo "Cleaned branch name: $cleanedBranchName"
          
          echo "branch_suffix=$cleanedBranchName" >> "$GITHUB_OUTPUT"

  compute-version:
    uses: ./.github/workflows/gradle.version.yaml

  build:
    needs: [ "compute-suffix", "compute-version" ]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: "📦 Checkout"
        uses: actions/checkout@v4

      - id: setupJava
        name: "🔧 Setup Java"
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - id: setupGradle
        name: "🔧 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - id: build
        name: "🏗️ Build"
        run: ./gradlew --build-cache ${{ inputs.gradle_tasks }}
        env:
          Version: "${{ needs.compute-version.outputs.version }}-${{ needs.compute-version.outputs.minecraft_version }}-build-${{ steps.compute-suffix.outputs.branch_suffix }}"