name: Common Version Determination CI

on:
  workflow_call:
    inputs:
      suffix:
        description: "The release suffix"
        type: string
    outputs:
      minecraft_version:
        description: "The minecraft version"
        value: ${{ jobs.compute-version.outputs.minecraft_version }}
      mod_version:
        description: "The mod version"
        value: ${{ jobs.compute-version.outputs.version }}
      suffix:
        description: "The input suffix"
        value: ${{ inputs.suffix }}
      full_version:
        description: "The full version string"
        value: ${{ jobs.compute-version.outputs.full_version }}
      tag_version:
        description: "The version that the tag should get"
        value: ${{ jobs.compute-version.outputs.tag_version }}

permissions:
  contents: read

jobs:
  compute-version:
    runs-on: ubuntu-latest
    outputs:
      minecraft_version: ${{ steps.minecraftVersion.outputs.minecraft_version }}
      mod_version: ${{ steps.version.outputs.version }}
      full_version: ${{ steps.fullVersion.outputs.full_version }}
      tag_version: ${{ steps.tagVersion.outputs.tag_version }}
    steps:
      - id: checkout
        name: "📦 Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: minecraftVersion
        name: "📦 Extract Minecraft version"
        run: |
          cat gradle.properties | grep exactMinecraftVersion | cut -d "=" -f 2 > minecraft_version.txt
          echo "Minecraft version: $(cat minecraft_version.txt)"
          echo "minecraft_version=$(cat minecraft_version.txt)" >> "$GITHUB_OUTPUT"

      - id: modVersion
        name: "🔢 Compute version"
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v${{ steps.minecraftVersion.outputs.minecraft_version }}-"
          search_commit_body: true
          debug: true
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"

      - id: fullVersion
        name: "Generate full version"
        run: |
          full_version="${{ steps.modVersion.outputs.version }}-${{ steps.minecraftVersion.outputs.minecraft_version }}-${{ inputs.suffix }}"
          echo "Full version: ${full_version}"
          echo "full_version=${full_version}" >> "$GITHUB_OUTPUT"

      - id: tagVersion
        name: "Generate tag version"
        run: |
          tag_version="v${{ steps.minecraftVersion.outputs.minecraft_version }}-${{ steps.modVersion.outputs.version }}"
          echo "Full version: ${full_version}"
          echo "tag_version=${tag_version}" >> "$GITHUB_OUTPUT"